<?xml version="1.0" ?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd" [
    <!ELEMENT coverage (sources?, packages)>
    <!ATTLIST coverage line-rate CDATA #REQUIRED>
    <!ATTLIST coverage branch-rate CDATA #REQUIRED>
    <!ATTLIST coverage lines-covered CDATA #REQUIRED>
    <!ATTLIST coverage lines-valid CDATA #REQUIRED>
    <!ATTLIST coverage branches-covered CDATA #REQUIRED>
    <!ATTLIST coverage branches-valid CDATA #REQUIRED>
    <!ATTLIST coverage complexity CDATA #REQUIRED>
    <!ATTLIST coverage version CDATA #REQUIRED>
    <!ATTLIST coverage timestamp CDATA #REQUIRED>
    <!ELEMENT sources (source)*>
    <!ELEMENT source (#PCDATA)>
    <!ELEMENT packages (package)*>
    <!ELEMENT package (classes)>
    <!ATTLIST package name CDATA #REQUIRED>
    <!ATTLIST package line-rate CDATA #REQUIRED>
    <!ATTLIST package branch-rate CDATA #REQUIRED>
    <!ATTLIST package complexity CDATA #REQUIRED>
    <!ELEMENT classes (class)*>
    <!ELEMENT class (methods, lines)>
    <!ATTLIST class name CDATA #REQUIRED>
    <!ATTLIST class filename CDATA #REQUIRED>
    <!ATTLIST class line-rate CDATA #REQUIRED>
    <!ATTLIST class branch-rate CDATA #REQUIRED>
    <!ATTLIST class complexity CDATA #REQUIRED>
    <!ELEMENT methods (method)*>
    <!ELEMENT method (lines)>
    <!ATTLIST method name CDATA #REQUIRED>
    <!ATTLIST method signature CDATA #REQUIRED>
    <!ATTLIST method line-rate CDATA #REQUIRED>
    <!ATTLIST method branch-rate CDATA #REQUIRED>
    <!ATTLIST method complexity CDATA #REQUIRED>
    <!ELEMENT lines (line)*>
    <!ELEMENT line (conditions)*>
    <!ATTLIST line number CDATA #REQUIRED>
    <!ATTLIST line hits CDATA #REQUIRED>
    <!ATTLIST line branch CDATA "false">
    <!ATTLIST line condition-coverage CDATA "100%">
    <!ELEMENT conditions (condition)*>
    <!ELEMENT condition EMPTY>
    <!ATTLIST condition number CDATA #REQUIRED>
    <!ATTLIST condition type CDATA #REQUIRED>
    <!ATTLIST condition coverage CDATA #REQUIRED>
]>
<coverage branch-rate="0" branches-covered="0" branches-valid="0" complexity="0" line-rate="0.3243" lines-covered="12" lines-valid="37" timestamp="1564551215562" version="4.5.4">
	<!-- Generated by coverage.py: https://coverage.readthedocs.io -->
	<!-- Based on https://raw.githubusercontent.com/cobertura/web/master/htdocs/xml/coverage-04.dtd -->
	<sources>
		<source>/app</source>
	</sources>
	<packages>
		<package branch-rate="0" complexity="0" line-rate="0.3243" name=".">
			<classes>
				<class branch-rate="0" complexity="0" filename="index.py" line-rate="0.75" name="index.py">
					<methods/>
					<lines>
						<line hits="1" number="1"/>
						<line hits="1" number="2"/>
						<line hits="1" number="3"/>
						<line hits="0" number="5"/>
						<line hits="1" number="7"/>
						<line hits="1" number="8"/>
						<line hits="1" number="10"/>
						<line hits="0" number="11"/>
					</lines>
				</class>
				<class branch-rate="0" complexity="0" filename="request.py" line-rate="0" name="request.py">
					<methods/>
					<lines>
						<line hits="0" number="3"/>
						<line hits="0" number="4"/>
						<line hits="0" number="5"/>
						<line hits="0" number="7"/>
						<line hits="0" number="9"/>
						<line hits="0" number="11"/>
						<line hits="0" number="14"/>
						<line hits="0" number="16"/>
						<line hits="0" number="18"/>
						<line hits="0" number="19"/>
						<line hits="0" number="20"/>
						<line hits="0" number="22"/>
						<line hits="0" number="24"/>
						<line hits="0" number="25"/>
						<line hits="0" number="26"/>
						<line hits="0" number="28"/>
						<line hits="0" number="29"/>
					</lines>
				</class>
				<class branch-rate="0" complexity="0" filename="test_index.py" line-rate="1" name="test_index.py">
					<methods/>
					<lines>
						<line hits="1" number="1"/>
						<line hits="1" number="2"/>
						<line hits="1" number="4"/>
						<line hits="1" number="5"/>
						<line hits="1" number="7"/>
						<line hits="1" number="8"/>
					</lines>
				</class>
				<class branch-rate="0" complexity="0" filename="text_index.py" line-rate="0" name="text_index.py">
					<methods/>
					<lines>
						<line hits="0" number="1"/>
						<line hits="0" number="2"/>
						<line hits="0" number="4"/>
						<line hits="0" number="5"/>
						<line hits="0" number="7"/>
						<line hits="0" number="8"/>
					</lines>
				</class>
			</classes>
		</package>
	</packages>
</coverage>
